weights: yolov5s.pt
cfg: animals/yolov5s.yaml
data: animals/my_voc.yaml
hyp:
  lr0: 0.0012
  lrf: 0.083
  momentum: 0.92
  weight_decay: 0.0004
  warmup_epochs: 5.0
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1
  box: 0.05
  cls: 0.8
  cls_pw: 1.2
  obj: 0.7
  obj_pw: 1.0
  iou_t: 0.15
  anchor_t: 3.5
  fl_gamma: 0.5
  hsv_h: 0.01
  hsv_s: 0.5
  hsv_v: 0.3
  degrees: 5.0
  translate: 0.05
  scale: 0.3
  shear: 2.0
  perspective: 5.0e-05
  flipud: 0.0
  fliplr: 0.3
  mosaic: 0.0
  mixup: 0.0
  copy_paste: 0.0
  green_suppress: 0.7
  non_green_boost: 1.3
epochs: 150
batch_size: 32
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
evolve_population: data\hyps
resume_evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: true
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: runs\train
name: green_special
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.1
patience: 100
freeze:
- 0
save_period: -1
seed: 0
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
ndjson_console: false
ndjson_file: false
save_dir: runs\train\green_special3
