#!/usr/bin/env python3

import rclpy
from rclpy.node import Node
from std_msgs.msg import Bool
from gpiozero import OutputDevice


class BuzzerController(Node):
    def __init__(self):
        super().__init__('buzzer_controller')

        # 初始化 GPIO控制蜂鸣器（BCM 编号）
        self.buzzer = OutputDevice(17) 

        # 创建订阅者
        self.subscription = self.create_subscription(
            Bool,
            'control_buzzer',
            self.listener_callback,
            10
        )
        self.get_logger().info('Buzzer Controller Node has been started.')

    def listener_callback(self, msg):
        if msg.data:
            self.buzzer.on()
            self.get_logger().info('Buzzer ON')
        else:
            self.buzzer.off()
            self.get_logger().info('Buzzer OFF')


def main(args=None):
    rclpy.init(args=args)
    node = BuzzerController()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.buzzer.off()
        node.destroy_node()
        rclpy.shutdown()
